# Generated by Django 2.2.4 on 2021-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0002_auto_20210806_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
