# Generated by Django 2.2.4 on 2021-08-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0003_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='shelter',
        ),
    ]
