# Generated by Django 2.2.4 on 2021-08-06 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0004_remove_animal_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adoption_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_arrival',
            field=models.CharField(blank=True, default=datetime.date.today, max_length=25),
        ),
    ]
