# Generated by Django 2.2.4 on 2021-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolt', '0006_adopterinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopterinfo',
            name='animal_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
